import '@styles/globals.css';
import Navbar from '../components/Navbar'
import React from 'react';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const RootLayout = ({ children })=> {
 return (
  <html lang='en'>
  <body>
  <Navbar />
      <div className='main'>

       <div className='gradient'>
       <main className='app'>
            {children}
          </main>
       </div>
      </div>
  </body>
</html>
  )
}

export default RootLayout